// TODO Add more or replace entirely the facts below for your chosen history domain
// Include at least 10 distinct facts with a 4-digit year included in the text for each
module.exports = {
    "FACTS_EN": [
      "Life is about making an impact, not making an income. In 2015 by Kevin Kruse",
      "Whatever the mind of man can conceive and believe, it can achieve. Napoleon Hill born 1883",
      "Strive not to be a success, but rather to be of value. Albert Einstein, 1879",
      "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.  Robert Frost born 1874",
      "I attribute my success to this: I never gave or took any excuse. Florence Nightingale born 1820",
      "You miss 100% of the shots you don’t take. Wayne Gretzky born 1961",
      "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed. Michael Jordan born 1963",
      "The most difficult thing is the decision to act, the rest is merely tenacity. Amelia Earhart. On July 2, 1937, the Lockheed aircraft carrying American aviator Amelia Earhart and navigator Frederick Noonan is reported missing near Howland Island in the Pacific.",
      "Every strike brings me closer to the next home run. Babe Ruth, born 1895, American professional baseball player",
      "Definiteness of purpose is the starting point of all achievement. W Clement Stone, died 2002, was a businessman, philanthropist and New Thought self-help book author.",
      "Life isn't about getting and having, it's about giving and being. Kevin Kruse, a popular keynote speaker, 2017.",
      "Life is what happens to you while you’re busy making other plans. John Lennon, assesinated in 1980.",
      "We become what we think about. Earl Nightingale, born 1921, adio personality, writer, speaker, and author",
      "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover. Mark Twain, born 1835, American writer.",
      "Life is 10% what happens to me and 90% of how I react to it. Charles Swindoll, born 1934, evangelical pastor.",
      "The most common way people give up their power is by thinking they don’t have any. Alice Walker, born 1944, American novelist, short story writer, poet, and activist.",
      "The mind is everything. What you think you become.  Buddha, could be alive today in 2017.",
      "The best time to plant a tree was 20 years ago. The second best time is now. Chinese Proverb. Toilet paper was invented by the Chinese once upon of time; the first modern toilet paper was available in 1857.",
      "An unexamined life is not worth living. Socrates. The quote on philosophy and the footnotes to Plato was writen in 1979 by Alfred North Whitehead.",
      "Eighty percent of success is showing up. Woody Allen, born 1935.",
      "Your time is limited, so don’t waste it living someone else’s life. Steve Jobs, dead 2011.",
      "Winning isn’t everything, but wanting to win is. Vince Lombardi, born 1913, American football player, coach, and executive in the National Football League.",
      "I am not a product of my circumstances. I am a product of my decisions. Stephen Covey, dead 2012, his most popular book was The 7 Habits of Highly Effective People.",
      "Every child is an artist.  The problem is how to remain an artist once he grows up. Pablo Picasso, born 1881 in Malaga.",
      "You can never cross the ocean until you have the courage to lose sight of the shore. Christopher Columbus, circa 1492.",
      "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. Maya Angelou, dead 2014, an American poet, memoirist, and civil rights activist.",
      "Either you run the day, or the day runs you. Jim Rohn, dead 2009, an American entrepreneur, author and motivational speaker.",
      "Whether you think you can or you think you can’t, you’re right. Henry Ford, dead 1947, is the seventh-wealthiest figure of the modern period (net worth of $188–199 billion).",
      "The two most important days in your life are the day you are born and the day you find out why. Mark Twain, dead 1910, an American writer, humorist, entrepreneur, publisher, and lecturer.",
      "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it. Johann Wolfgang von Goethe, born 1749.",
      "The best revenge is massive success. –Frank Sinatra, dead 1998, was one of the most popular and influential musical artists of the 20th century.",
      "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily. Zig Ziglar, dead 2012, god of the salesmen.",
      "Life shrinks or expands in proportion to one's courage. Anais Nin, an essayist and memoirist born in 1903 to Cuban parents in France, where she was raised. She lived most of her life in the United States, where she became an established author.",
      "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for. Epicurus, around 2300 years ago.",
      "Death does not concern us, because as long as we exist, death is not here. And when it does come, we no longer exist. Epicurus cited in 2013 by Lars Von Trier.",
      "If God listened to the prayers of men, all men would quickly have perished: for they are forever praying for evil against one another. Epicurus, cited by Hume in 1748 in his book An Enquiry Concerning Human Understanding.",
      "You don't develop courage by being happy in your relationships everyday. You develop it by surviving difficult times and challenging adversity. Epicurus, cited by Schopenhauer, who died in 1860.",
      "It is folly for a man to pray to the gods for that which he has the power to obtain by himself. Epicurus, cited by Nietzsche in the Gay Science in 1882.",
      "If life was fair, Elvis would be alive and all the impersonators would be dead. Johnny Carson, died 2005",
      "It is dangerous to be right in matters on which the established authorities are wrong. Voltaire, born 1694, French Enlightenment writer, historian, and philosopher.",
      "Millions yearn for immortality who don't know what to do with themselves on a rainy Sunday afternoon. Susan Ertz, Anglo-American writer, known for her sentimental tales of genteel life in the country. Born 1894.",
      "No issue is so small that it can't be blown out of proportion. Stuart Hughes, Canadian actor born 1959.",
      "The lion and the calf shall lie down together but the calf won't get much sleep. Woody Allen, born 1935.",
      "The race is not always to the swift, nor the battle to the strong - but that's the way to bet. Damon Runyon, an American newspaperman and short story writer, died in 1946.",
      "The trouble with being punctual is that nobody's there to appreciate it. Franklin P. Jones, born 1908.",
      "There are two kinds of people, those who do the work and those who take the credit. Try to be in the first group; there is less competition there.  Indira Gandhi, Indian politician assesinated in 1984.",
      "When a stupid man is doing something he is ashamed of, he always declares that it is his duty. George Bernard Shaw, died 1950, Irish playwright.",
      "It is the dull man who is always sure, and the sure man who is always dull.  H. L. Mencken, born 1880, American journalist, satirist, cultural critic and scholar of American English.",
      "A great many people think they are thinking when they are merely rearranging their prejudices. William James, died 1910, reference to American psychologists.",
      "I loathe people who keep dogs. They are cowards who havent got the guts to bite people themselves. August Strindberg, died 1912, Swedish playwright.",
      "It is a miracle that curiosity survives formal education. Albert Einstein, born 1879.",
      "All that is necessary for the forces of evil to take root in the world is for enough good men to do nothing.  Edmund Burke, Irish statesman, died 1797.",
      "I find television very educational. Every time someone switches it on I go into another room and read a good book. Groucho Marx. The first movie or the Marx brothers was a silent film made in 1921 that was never released.",
      "People will accept your ideas much more readily if you tell them Benjamin Franklin said it first. Franklin was one of the Founding Fathers. In recognition of his work with electricity, he received the Royal Society's Copley Medal in 1753.",
      "The two most common elements in the universe are hydrogen and stupidity. Isaac Asimov, science fiction guru, died 1992.",
      "Compromise is the art of dividing a cake so everyone believes he got the biggest piece. Ludwig Erhard, second Chancellor of the Federal Republic of Germany from 1963.",
      "Its extremely unlucky to be superstitious, for no other reason than it is always unlucky to be colossally stupid. Stephen Fry,  American author. His book, The Long Trail Home Broadman & Holman, won the 2002 Christy Award in the category western novel.",
      "Opportunity is missed by most people because it is dressed in overalls and looks like work. Thomas Edison. His first successful test of the incandescent light bulb was on October 22, 1879.",
      "Dont go around saying the world owes you a living. The world owes you nothing; it was here first. Mark Twain. The adventures of Tow Saywer was first published in 1884.",
      "A good plan today is better than a perfect plan tomorrow. George Patton, best known for his leadership of the U.S. Third Army in France and Germany following the Allied invasion of Normandy in June 1944.",
      "Man will occassionally stumble over the truth, but most of the time he will pick himself up and continue on. Winston Churchill, served as Prime Minister of the United Kingdom starting in 1940.",
      "It is better to have enough ideas for some of them to be wrong than to always be right by having no ideas at all. Edward de Bono, born 1933, Maltese physician, psychologist, author, inventor and consultant psychologist.",
      "The world is moving so fast these days that the man who says it cant be done is generally interrupted by someone doing it. Elbert Hubbard, American writer, author of an indie film already in 1915.",
      "The only difference between me and a madman is that Im not mad.  Salvador Dali, surrealist artist, co-authored the movie An andalusian dog in 1929.",
      "Never interrupt your enemy when he is making a mistake. Napoleon Bonaparte, buried in 1840 in Paris 19 years after his death.",
      "A witty saying proves nothing. Voltaire. On 2 July 1778, Rousseau died one month after Voltaire's death.",
      "The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt.  Bertrand Russell, in 1950 was awarded the Nobel Prize in Literature.",
      "It is better to remain silent and be thought a fool than to open ones mouth and remove all doubt.  Mark Twain. His 1889 novel A Connecticut Yankee in King Arthur's Court features a time traveler from the contemporary U.S.",
      "It is best to mince ones words very finely, it makes them much easier to eat afterwards. Oscar Wilde, Irish playwright, his Picture of Dorian Gray was first published in 1890.",
      "Underneath the skin, all humanity are brothers and I would gladly skin humanity alive to prove it.  Ellsworth Toohey is a fictional character in The Fountainhead, a 1943 novel by Ayn Rand ",
      "There is nothing either good or bad, but thinking makes it so.  Shakespeare, dead 1616.",
      "I guess when you turn off the main road, you have to be prepared to see some funny houses. Stephen King, published his first novel in 1977.",
      "It isnt pollution thats harming the environment, its the impurities in our air and water that are doing it. Dan Quayle, US Vice President in 1989.",
      "Everything that can be invented has been invented. Charles H. Duell, Commissioner, U.S. Office of Patents, 1899.",
      "The abdomen, the chest, and the brain will forever be shut from the intrusion of the wise and humane surgeon. Sir John Eric Ericksen, British surgeon, appointed Surgeon-Extraordinary to Queen Victoria 1873.",
      "Louis Pasteurs theory of germs is ridiculous fiction.Pierre Pachet, Professor of Physiology at Toulouse, 1872",
      "Who the hell wants to hear actors talk? H.M. Warner, Warner Brothers, 1927.",
      "We dont like their sound, and guitar music is on the way out. Decca Recording Company rejecting the Beatles, 1962.",
      "Heavier-than-air flying machines are impossible. Lord Kelvin, president, Royal Society, 1895."
    ]
}
